repos:
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3.8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'
    hooks:
    - id: mypy
      args: [--strict, --ignore-missing-imports]

  -   repo: https://github.com/pycqa/pydocstyle
      rev: 6.0.0  # pick a git hash / tag to point to
      hooks:
      - id: pydocstyle